language: emacs

env:
  - "CHECK_TARGET=check-core  LISP=sbcl  EMACS=emacs24"
  - "CHECK_TARGET=check-core  LISP=cmucl EMACS=emacs24"
  - "CHECK_TARGET=check-core  LISP=ccl   EMACS=emacs24"
  - "CHECK_TARGET=check-fancy LISP=sbcl  EMACS=emacs24"
  - "CHECK_TARGET=check-fancy LISP=cmucl EMACS=emacs24"
  - "CHECK_TARGET=check-fancy LISP=ccl   EMACS=emacs24"

  # also, for emacs24/sbcl test some more contribs in isolation
  - "CHECK_TARGET=check-mrepl LISP=sbcl EMACS=emacs24"
  - "CHECK_TARGET=check-indentation LISP=sbcl EMACS=emacs24"

install:
  - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24-nox;
    fi

script:
  - make LISP=$LISP EMACS=$EMACS $CHECK_TARGET
